name: Build and Release Ironuki GUI

on:
  push:
    tags:
      - "v*" # This is for release builds, triggering when you push version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      # Install Python 3.9 on macOS
      - name: Install Python 3.9 on macOS
        if: runner.os == 'macOS'
        run: |
          brew install python@3.9
          python3 --version

      # Install Python 3.9 and dependencies on Ubuntu
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.9 make gcc libxtst-dev libx11-dev
          python3 --version

      # Install Python 3.9 on Windows
      - name: Install Python 3.9 on Windows
        if: runner.os == 'Windows'
        run: |
          choco install python --version=3.9.10
          python --version

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm install

      # Run the Ironuki GUI npx command
      - name: Run Ironuki GUI
        run: npx ironuki

      # Build and test npx command
      - name: Build and test npx command
        run: echo "Building and testing on ${{ matrix.os }} complete"

      # Optional: Upload artifacts for each OS build
      - name: Upload Windows Executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-windows
          path: dist/*.exe

      - name: Upload macOS Binary
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-macos
          path: dist/*.dmg

      - name: Upload Ubuntu .deb File
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-ubuntu
          path: dist/*.deb
