name: Build and Release Ironuki GUI

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      # Ensure node-gyp uses Python 3.9 on macOS without installing
      - name: Force node-gyp to use Python 3.9 on macOS
        if: runner.os == 'macOS'
        run: |
          # Force node-gyp to use Python 3.9 (assumed to already exist on the runner)
          export PYTHON=$(which python3.9)
          echo "Using PYTHON from $PYTHON"
          python3.9 --version
          # Install Xcode command line tools (needed for native module compilation)
          xcode-select --install || echo "Xcode Command Line Tools already installed"
          clang --version
          make --version

      # Install Python 3.9 and dependencies on Ubuntu
      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.9 make gcc libxtst-dev libx11-dev
          python3 --version

      # Install Python 3.9 on Windows
      - name: Install Python 3.9 on Windows
        if: runner.os == 'Windows'
        run: |
          choco install python --version=3.9.10
          python --version

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: |
          export PYTHON=$(which python3.9)  # Ensure node-gyp uses Python 3.9
          npm install

      # **Build the Electron App**
      - name: Build Electron App
        run: |
          export PYTHON=$(which python3.9)  # Ensure node-gyp uses Python 3.9 during build
          npm run build  # Run your Electron build command (adjust if needed)

      # Upload Windows Executable
      - name: Upload Windows Executable
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-windows
          path: dist/*.exe

      # Upload macOS Binary
      - name: Upload macOS Binary
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-macos
          path: dist/*.dmg

      # Upload Ubuntu .deb File
      - name: Upload Ubuntu .deb File
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: ironuki-ubuntu
          path: dist/*.deb
