name: Build and Test Ironuki

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Set up Python (latest)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.0"

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || echo "Xcode Command Line Tools already installed"
          npm config set python $(which python3)
          node-gyp configure

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc libxtst-dev libx11-dev
          python3 --version
          npm config set python $(which python3)
          node-gyp configure

      - name: Install Node.js dependencies
        run: |
          npm install -g node-gyp
          npm install

      - name: Run npx ironuki
        run: npx ironuki

      - name: Build and test npx command
        run: echo "Building and testing on ${{ matrix.os }} complete"
